### ISSUE TITLE
Error parsing frame data: Cannot save enum schema

### ISSUE THREAD

**Issue by shalomvolchok** [confluentinc/bottledwater-pg#18]
Hey Martin!

First, thanks for sharing your work!! And for sharing so much online about logs, samza, and kafka. Awesome stuff!!

After getting your docker examples to work, I was trying with a bigger database and ran into this error in the bottledwater client logs:

`Error parsing frame data: Cannot save enum schema`

It seems I can reprodue it with a one table example by using any combination of two timestamp / date columns. If I run the docker examples and insert the following into Postgres, then I get that error in the client logs. Either column alone seems to work fine.

```
create table two_dates (id serial primary key, timestamp_field timestamp, date_field date);

insert into two_dates (timestamp_field, date_field) values('June 17 16:05:06 2015 PST','4/24/2016');
```

What do you think? Am I doing something terribly wrong?

Best,
Shalom

**Comment by ept** [comment]
Thanks for reporting this. I can reproduce it, and yes, it's a bug. I'll try to find the time to dig into it soon.

**Comment by shalomvolchok** [comment]
You're welcome. Seems like this will be super useful and we are looking forward to working with it more.

**Comment by scbrady** [comment]
I am having the same issue, and I was just looking through the code in oid2avro.c (lines 242-258 as of the time of this comment)

```c
        /* Date/time types. We don't bother with abstime, reltime and tinterval (which are based
         * on Unix timestamps with 1-second resolution), as they are deprecated. */
        case DATEOID:        /* date: 32-bit signed integer, resolution of 1 day */
            return schema_for_date();
        case TIMEOID:        /* time without time zone: microseconds since start of day */
            value_schema = avro_schema_long();
            break;
        case TIMETZOID:      /* time with time zone, timetz: time of day with time zone */
            value_schema = schema_for_time_tz();
            break;
        case TIMESTAMPOID:   /* timestamp without time zone: datetime, microseconds since epoch */
            return schema_for_timestamp(false);
        case TIMESTAMPTZOID: /* timestamp with time zone, timestamptz: datetime with time zone */
            return schema_for_timestamp(true);
        case INTERVALOID:    /* @ <number> <units>, time interval */
            value_schema = schema_for_interval();
            break;
```


It seems as though dates are the only thing you use a return on, everything else you add it to value_schema and then break from the switch statement.

There is a very good chance this has nothing to do with it, but I was just looking through quickly before I got off of work and this is what I found. I'll try changing this and seeing if it helps when I get back to work next week if you don't get to it first.

Thanks!

**Comment by ept** [comment]
@scbrady I don't think that's the issue — the code is written like that deliberately (in order to account for Avro types that already provide a union type wrapper), although I agree the code is a bit nasty.

I think the problem is that two Avro record types with the same name (in this case, `DateTime`) are being defined — one for each timestamp column — and the resolution mechanism isn't working correctly. This may be a bug in libavro, but I've not yet had a chance to look into it deeper. (Pull requests welcome if anyone wants to dig into it.)

**Comment by scbrady** [comment]
@ept That makes a lot more sense now that I actually had some time to look at it, good call.

I pulled down the libavro code and took a look at it as well and it does not seem like it has a resolution mechanism at all for records with the same name.

It seems like there are only two ways to get around this now (besides editing the libavro code).
1). Making sure that each `avro_schema_record` call gets a unique name (eg. Date1, Date2)
2). Making sure that each `avro_schema_record` call gets a unique namespace (eg. com.martinkl.bottledwater.{column_name}.datatypes

I'm leaning more towards option 2 because that means I would only have to pass around the column name to a few more functions to get it working. However, I don't know if changing the namespacing you have set up will break other things. Does this sound like a good way to get around this problem?

**Comment by scbrady** [comment]
@ept I worked on this bug most of the day and it doesn't make sense to me. I made it so that the `avro_schema_record` call received a unique name (which didn't work) and then a unique namespace (which also didn't work). It still gives me the `Error parsing frame data: Cannot save enum schema` error.

I've also been combing through the libavro code and I can't find the reason it errors out. I'm going to try to look at it more, but if I can't get it, I'll just make all of the date formats strings. Let me know if you have any luck with it.

**Comment by ept** [comment]
@scbrady Thanks for looking into this. Avro allows the same record type to be referenced multiple times: see [the spec](http://avro.apache.org/docs/1.7.7/spec.html#Names). The first time a record type occurs its type is defined, and thereafter the schema can refer to it by fully-qualified name. Perhaps the oid2avro schema generation mechanism needs to track which record types have already been defined, and thus resolve duplicates itself.

**Comment by scbrady** [comment]
@ept Thanks for the info, maybe I should look more into the docs before spending so much time looking at the code!

What you're saying makes sense, but for the life of me I can't figure out how to just reference the record. I figured out that `avro_schema_record` calls an init method behind the scenes, and that's why it errors out when it collides with the one already in existence.

All that said, I did manage to fix it enough for me by changing the names like I said I was trying to yesterday. The reason it didn't work is because I was giving the record schema a unique name (eg. columnName_Date), but not the enum. Once I gave the enum a unique name as well (eg. columnName_SpecialTime), everything works.

I image that you will want to come up with a more elegant solution (perhaps referencing the already created record schema by name) for the official patch to this bug, so I'll hold off on submitting a pull request. If you do want this solution as a hotfix that you will work on later, just let me know and I'll submit the request.

**Comment by bmorton** [comment]
@scbrady do you have code in a branch somewhere that I can take a look at to get familiar with this?

**Comment by scbrady** [comment]
@bmorton I forked this project here: https://github.com/scbrady/bottledwater-pg. I only had to change the file `oid2avro.c`. It's a hacky solution, but it definitely works.

**Comment by bmorton** [comment]
@ept have you had some time to take a look at this in depth?  @gotascii and I have been banging our heads on this one for a few days now and we tried to follow a couple of leads in this thread, but ultimately haven't come up with a fix yet.

We have a pretty simple case setup where this fails and the Avro schema that is generated looks [like this](https://gist.github.com/bmorton/33e572b9d5b2655d1a9e).  Is that the proper schema that should be generated?  Is it valid for the `DateTime` record to be defined twice like that?

We tried only defining the record once and then just referencing it, but it still ends up like that in the schema.  We tried using links, not really knowing what they're for, and ended up with some segfaults, so we didn't push much further down that path.

We'd love to keep digging, but we probably need some more pointers as to where to poke at more.

We also were able to use @scbrady's fix to some success, but around a couple hundred records or so, Postgres started segfaulting.

**Comment by scbrady** [comment]
@bmorton That's what I ran into as well. The only way that I could get mine to work reliably was to batch insert into Postgres with bottledwater turned off, then turn it on when I was not inserting into Postgres. For some reason, bottledwater can take a snapshot of a large table (I believe it was well over 100,000 rows), but it segfaults when you leave it on and are rapidly adding new rows. We could get it to work by making sure bottledwater was turned off when inserts were made, then turning it back on. Not a great solution, but maybe it could help you in the short run.

**Comment by bmorton** [comment]
Doing some more very, very rough debugging, I can get it past that error if I force [this Avro schema](https://gist.github.com/bmorton/33e572b9d5b2655d1a9e#file-valid_avro-json) to be used instead.

The difference on the second timestamp field, `updated_at`.  The Avro schema is this instead of just the redefinition again:

```json
{
  "name": "updated_at",
  "type": [
    {
      "type": "null"
    },
    {
      "type": "com.martinkl.bottledwater.datatypes.DateTime"
    },
    {
      "type": "SpecialTime"
    }
  ]
}
```

Any idea if this is a valid path to keep going down?  Any pointers as to what I might have to change to get this schema generated like this instead?

**Comment by bmorton** [comment]
Well, I'm a bit closer now!  I've got this working on my extremely simple example with an id, string, created_at, and updated_at.  When trying this on my actual application's schema, I still get a segfault in Postgres, so I'm assuming I've done something terrible in C as my code is pretty hacky.

[This branch](https://github.com/confluentinc/bottledwater-pg/compare/master...bmorton:use-links) appears to generate the correct Avro schema now got things flowing.  Basically, we had to rearrange the unioning logic so that we could use the fully defined record on the first use and links to the records on all subsequent references.

Like I said, my C isn't the best, but if it helps to open a pull request to start discussing more in depth, I'm happy to do that.  I'll need a bit of help figuring out if I need to get anything tested and some guidance on how to better implement the logic around first-time-use.  I'm also a bit unclear on when I need to reference count these things.  I fear that might be the source of my segfault right now.

**Comment by nailor** [comment]
@bmorton You think you could open a PR for this? It's something that is stopping me from using BottledWater at the moment

**Comment by ept** [comment]
Ok folks, I've just pushed a commit which should hopefully fix the issue (f5e5d833fa392d31d6859505f163a471967e2224). Sorry that it's taken me so long to get round to it. Could you test it please and see whether it solves your problem?

**Comment by bchazalet** [comment]
@ept it does for me!

**Comment by samstokes** [comment]
@ept I can confirm that with a build from revision f5e5d83, my case that was failing (an ActiveRecord-generated table with `created_at` and `updated_at` timestamps now works as expected.

However, some more recent commit since then seems to have broken it again.  The same test case on a build from revision 63d4d0e (latest master at time of writing) causes the Postgres backend to segfault when I create the table.

I've not had a chance to dig deeper into the crash, but I did notice that the crash seems to be instigated by the Bottled Water *client*.  When it first occurs, the client dies as well ("Could not receive replication data: server closed the connection unexpectedly").  Postgres restarts the affected backend, but when I restart the BW client and it reconnects, the backend segfaults again.

I was able to reproduce this using the provided Dockerfiles.

**Comment by ept** [comment]
@samstokes I'm confused by this statement: "the crash seems to be instigated by the Bottled Water client. When it first occurs, the client dies as well" — what indicates that the client is causing the crash?

I tried reproducing the crash, but didn't succeed in doing so in Docker — it works fine for me. As it seems to be unrelated to this issue #18, could you perhaps open a new issue with a bit more detail? Then I'll close this issue.

One thing worth noting: I made a breaking change to the wire protocol between PG extension and BW client in c71b8a4e3b9ea25f4292aa51d8bea0ed1fc0d680. So you need to make sure they are built from the same version of the code. (In principle, BW has the facility for backwards-compatible protocol changes, but it's a bit of faff and it adds cruft to the code. As BW isn't very widely used yet, I thought it's ok to make breaking changes at this stage.)

I'm pushing updated versions of the confluent/bottledwater and confluent/postgres-bw Docker images, built from the current master (63d4d0efad4541c41c798255539f584398a9ce57), in case that's useful.

**Comment by samstokes** [comment]
@ept sorry for my unclear wording.  I've had another go at describing the crash (which I can still reproduce with the rebuilt images) in #37.
